
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conersionEuroToFh", targetNamespace = "http://ws.example.org/", className = "proxy.ConersionEuroToFh")
    @ResponseWrapper(localName = "conersionEuroToFhResponse", targetNamespace = "http://ws.example.org/", className = "proxy.ConersionEuroToFhResponse")
    @Action(input = "http://ws.example.org/BanqueService/conersionEuroToFhRequest", output = "http://ws.example.org/BanqueService/conersionEuroToFhResponse")
    public double conersionEuroToFh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCOmpte", targetNamespace = "http://ws.example.org/", className = "proxy.GetCOmpte")
    @ResponseWrapper(localName = "getCOmpteResponse", targetNamespace = "http://ws.example.org/", className = "proxy.GetCOmpteResponse")
    @Action(input = "http://ws.example.org/BanqueService/getCOmpteRequest", output = "http://ws.example.org/BanqueService/getCOmpteResponse")
    public Compte getCOmpte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compteList", targetNamespace = "http://ws.example.org/", className = "proxy.CompteList")
    @ResponseWrapper(localName = "compteListResponse", targetNamespace = "http://ws.example.org/", className = "proxy.CompteListResponse")
    @Action(input = "http://ws.example.org/BanqueService/compteListRequest", output = "http://ws.example.org/BanqueService/compteListResponse")
    public List<Compte> compteList();

}
